### ISSUE TITLE
Why don't use the 80, 443 port in the container?

### ISSUE THREAD

**Issue by ghost** [qdm12/caddy-scratch#1]
Why don't use the 80, 443 port in the container?

**Comment by qdm12** [comment]
Hi there,

Because I run it without root (safer). So it cannot bind to ports under 1024 internally.

Note that I am trying to change the Docker image name to `qmcgaw/tinycaddy` as microbadger and shields.io don't pick up `qmcgaw/caddy-scratch` for some reason.

Thanks !

**Comment by qdm12** [comment]
Hi @ClarkeCheng ,

Never mind, I went back to `qmcgaw/caddy-scratch` it was a a link error (switching from Docker Hub to Docker Cloud builds).

I have added features to the readme. Let me know if you have any idea how to improve it or make it smaller 🚀
